# Generated by Django 3.1.4 on 2021-01-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogging', '0002_auto_20201229_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('profile_img', models.ImageField(default=False, upload_to='profile/')),
                ('dob', models.DateField()),
                ('qualification', models.CharField(blank=True, choices=[('ug', 'UnderGraduate'), ('g', 'Graduate'), ('pg', 'PostGraduate')], default=None, max_length=15)),
            ],
        ),
    ]
