# Generated by Django 3.1.4 on 2021-01-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Test')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categor_id',
            field=models.ManyToManyField(to='blogging.Categories'),
        ),
    ]
