# Generated by Django 3.1.4 on 2021-01-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_auto_20210106_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categor_id',
            new_name='category_id',
        ),
    ]
